name: Deploy to Apache2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install --prefix /home/runner/work/EI/EI/frontend

      - name: Build project
        run: npm run build -prefix /home/runner/work/EI/EI/frontend
        
      - name: SSH Deploy frontend
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: quoi-regarder.cs-campus.fr
          REMOTE_USER: ubuntu
          REMOTE_PORT: 22
          SCRIPT_BEFORE: |
            cd /var/www/
            sudo rm -rf html/
          SOURCE: "frontend/build/"
          TARGET: /var/www/html/
          SCRIPT_AFTER: |
            cd /var/www/
            ls -al
          
      - name: SSH Deploy backend
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: quoi-regarder.cs-campus.fr
          REMOTE_USER: ubuntu
          REMOTE_PORT: 22
          SCRIPT_BEFORE: |
            cd /var/www/
            ls -al
          SOURCE: "backend/"
          TARGET: /var/www/EI/
          SCRIPT_AFTER: |
            cd /var/www/
            ls -al
