name: Deploy to Apache2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install --prefix /home/runner/work/EI/EI/frontend

      - name: Build project
        run: npm run build -prefix /home/runner/work/EI/EI/frontend

      - name: SSH Deploy
        uses: easingthemes/ssh-deploy@v2.1.5
        with:
          REMOTE_HOST: 138.195.138.190
          REMOTE_USER: root
          REMOTE_PORT: 22
          SOURCE: build/
          TARGET: /var/www/
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
